spring.application.name=CampusVoice

#server.port=9098
#spring.mongodb.uri=mongodb+srv://armabir1_db_user:mongomongo@cluster-01.vclqq8p.mongodb.net/cms?appName=Cluster-01

# Database Connection
spring.mongodb.uri=${MONGO_URI}

# Server Port (Defaults to 8080, but respects Render's port if provided)
server.port=${PORT:9098}